### ISSUE TITLE
External accounts irc nickname modification test fails

### ISSUE THREAD

**Issue by comzeradd** [mozilla/mozillians-tests#225]
At 0906f706789c86b049d961b49af062db71bc083d the `test_that_user_can_modify_external_accounts_irc_nickname` was introduced that is [currently failing](https://webqa-ci.mozilla.com/job/mozillians.dev/354/testReport/tests.test_profile/TestProfile/test_that_user_can_modify_external_accounts_irc_nickname/) on dev.

The test fails when the user has no previous irc nickname, thus no `.nickname` class is rendered on the profile view.

Any ideas?

**Comment by davehunt** [comment]
Ideally the tests would control the user profile by creating a test user, but although we have this possibility with Personal, we'd need to complete the profile via the UI for every test. Instead, I would recommend that we ensure the user has an IRC nick configured. It also makes sense to mention this in the README for creating test users. Another option is to modify the test so that it passes when there is no initial IRC nick.

**Comment by davehunt** [comment]
I also noted some other prerequisites for the test accounts. For any test that opens the profile page from another user or when not logged in, the profile needs to be public. I found that setting the profile image and name to public was enough to do this. For the invite tests, the vouched user needs to be vouched at least three times in order to allowed to submit an invitation.

**Comment by dabiid** [comment]
I mentioned this in PR #208, I thought this might work. Let me know if it's worth fixing and I'll take a look at it again.

the test will fail if the nickname starts out empty. Is it worth handling that? It'd take something like this:

@property
def irc_nickname(self):
    try:
        return self.selenium.find_element(*self._irc_nickname_locator).text
    except NoSuchElementException:
        return ''
This shouldn't mask the selector breaking because the first assert would fail in that case (new_nickname == '').
