### ISSUE TITLE
Figure out why/fix 15 skipped tests against dev + staging environments, due to being classified as "sensitive" URLs

### ISSUE THREAD

**Issue by stephendonner** [mozilla/mozillians-tests#248]
(Putting this here, since it's more visible.)

15 tests are being skipped on dev + staging due to their base-urls being interpreted as "sensitive URLs" for those two test environments.

Dev: http://pastebin.com/9vVzidjx
Staging: http://pastebin.com/c626f3Ba

SKIP [15] /var/lib/jenkins/jobs/mozillians.stage/workspace/.venv/lib/python2.7/site-packages/pytest_selenium/safety.py:70: This test is destructive and the target URL is considered a sensitive environment. If this test is not destructive, add the 'nondestructive' marker to it. Sensitive URL: https://mozillians.allizom.org

I discovered this while working on a patch to switch this repo over to using tox, where these 15 run, and fail (which might be/probably is a separate, real issue?)

We should at least restore running these tests, so we can figure out what's wrong.

@davehunt - help, please?  :-\

**Comment by stephendonner** [comment]
Also, ping @comzeradd @akatsoulas @johngian - commits like https://github.com/mozilla/mozillians/commit/e4cc7ccd892dbe09ff5948b768c24fa2aa25857e have likely broken this Selenium WebDriver test coverage, and we just didn't know it, due to these skips :-(

**Comment by davehunt** [comment]
These were being skipped in Jenkins because pytest was resolving the root directory to the directory **above** the workspace, and therefore it didn't find the configuration file that sets the correct sensitive URL regex. It's been resolved by making sure the variables file is within the workspace (rather than in a temporary sibling directory) but could also be resolved by making sure the variables command line option doesn't include a space (this makes pytest think it may be a tests path). Let's open a new issue for any failures these previously skipped tests expose.
