### ISSUE TITLE
Cleanup group data after test runs

### ISSUE THREAD

**Issue by johngian** [mozilla/mozillians-tests#252]
Automated tests related to group functionality [1] create test data [2] for each testcase but never cleanup. This leads to thousands of `Group` entries in mozillians dev/stage. We should make sure that each testcase is atomic and cleans up testdata after each run. 

[1] https://github.com/mozilla/mozillians-tests/blob/master/tests/test_group.py
[2] https://github.com/mozilla/mozillians-tests/blob/master/tests/test_group.py#L23

**Comment by davehunt** [comment]
Can you provide some suggestions for how the tests could perform this cleanup? Is there an API call or would it need to be done via the UI? Note that if the latter, there may be instances where the cleanup is not successful depending on the test outcome.

**Comment by johngian** [comment]
There is no API for that so I guess this should be done using the UI. I understand that depending on the test result this might fail. What if we always setup/teardown test data using xunit style setup?

http://docs.pytest.org/en/latest/xunit_setup.html

**Comment by davehunt** [comment]
We can do it with fixtures rather than mixing our tests with xunit style. We could create a fixture that creates the group through the UI, yields the name of the group, and then removes it via the UI. The test can then use the group name to either directly load the page via URL or navigate to it another way. It would be much more awesome if we could do this via an API though. 😄

**Comment by johngian** [comment]
I am more familiar with xunit style and it was the first thing that came in mind.

+1 for the fixtures
